### ISSUE TITLE
ExternalDNS can inadvertently stop UniFi from providing dhcp/dns.

### ISSUE THREAD

**Issue by kashalls** [kashalls/external-dns-unifi-webhook#104]
### Bug Description

@rodent1 found that in some very rare cases ExternalDNS will create two `cname` records with identical key's and different values. 

Dnsmasq does not support having more than one `cname` record for a given key. Setting the record using the UniFi API will cause dnsmasq to not restart and will stop issuing dhcp and dns requests until the offending cname record is created. For some reason this seems to bypass any checks that I would think UniFi would have on their API.

The current fix when encountering this is to delete the HTTPRoute, then let external-dns & any cd pipeline sync.

### ExternalDNS Configuration

```yaml
    image:
      repository: registry.k8s.io/external-dns/external-dns
      tag: v0.16.1
    provider:
      logLevel: debug
      name: webhook
    triggerLoopOnEvent: true
    policy: sync
    sources: ["gateway-httproute", "service"]
    txtOwnerId: main
    txtPrefix: k8s.main.
    domainFilters: ["domain.example"]
```

### ExternalDNS Logs

ExternalDNS reports generating two targets for a single HTTPRoute record. The resource in kubernetes only shows the `external` parentRef where as the incoming change shows only an `internal` parentRef.

### Webhook Logs

Nothing of importance in webhook logs :(

### UniFiOS Version

4.2.4

### UniFi Network Version

9.1.105

### ExternalDNS Version

0.16.1

### Search

- [x] I have searched the open and closed issues for duplicates

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
