### ISSUE TITLE
HTTP Routes swapping from one Gateway to another will cause CNAME Error

### ISSUE THREAD

**Issue by kashalls** [kashalls/external-dns-unifi-webhook#111]
### Bug Description

HTTP Routes swapping from one Gateway to another will cause CNAME Error

### ExternalDNS Configuration

```yaml
    fullnameOverride: *app
    logLevel: &logLevel debug
    provider:
      name: webhook
      webhook:
        image:
          repository: ghcr.io/kashalls/external-dns-unifi-webhook
          tag: v0.5.2@sha256:e1eef62e8d9f1966def6f2efc89ff42bcaba1060b0c2957d9cab57a11c900d5c
        env:
          - name: LOG_LEVEL
            value: *logLevel
          - name: UNIFI_HOST
            value: "https://unifi"
          - name: UNIFI_API_KEY
            valueFrom:
              secretKeyRef:
                name: &secret external-dns-unifi-secret
                key: UNIFI_API_KEY
    policy: sync
    sources: ["gateway-httproute", "service"]
    txtOwnerId: default
    txtPrefix: k8s.
```

### ExternalDNS Logs

```text
time="2025-04-19T16:07:00Z" level=debug msg="Failed to apply changes with code 500"
time="2025-04-19T16:07:00Z" level=error msg="Failed to do run once: soft error\nfailed to apply changes with code 500"
W0419 16:07:02.162170       1 transport.go:356] Unable to cancel request for *instrumented_http.Transport
W0419 16:07:02.162295       1 transport.go:356] Unable to cancel request for *instrumented_http.Transport
W0419 16:07:02.162525       1 transport.go:356] Unable to cancel request for *instrumented_http.Transport
W0419 16:07:02.162549       1 transport.go:356] Unable to cancel request for *instrumented_http.Transport
W0419 16:07:02.162881       1 transport.go:356] Unable to cancel request for *instrumented_http.Transport
W0419 16:07:02.162897       1 transport.go:356 Unable to cancel request for *instrumented_http.Transport
```

### Webhook Logs

```text
{"level":"debug","ts":1745078820.8098109,"caller":"unifi/client.go:209","msg":"fetched records","count":66}
{"level":"debug","ts":1745078820.8201542,"caller":"http/server.go:2294","msg":"executing plan changes","req_method":"POST","req_path":"/records","create":3,"update_old":0,"update_new":0,"delete":0}
{"level":"error","ts":1745078820.8202312,"caller":"unifi/provider.go:85","msg":"failed to create endpoint","data":"echo.ok8.sh 0 IN CNAME  external.ok8.sh;internal.ok8.sh []","error":"CNAME records can only contain 1 target. There is likely a misconfiguration with one or more of your resources.","stacktrace":"github.com/kashalls/external-dns-unifi-webhook/internal/unifi.(*UnifiProvider).ApplyChanges\n\t/build/internal/unifi/provider.go:85\ngithub.com/kashalls/external-dns-unifi-webhook/pkg/webhook.(*Webhook).ApplyChanges\n\t/build/pkg/webhook/webhook.go:145\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2294\ngithub.com/go-chi/chi/v5.(*Mux).routeHTTP\n\t/go/pkg/mod/github.com/go-chi/chi/v5@v5.2.1/mux.go:480\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2294\ngithub.com/go-chi/chi/v5.(*Mux).ServeHTTP\n\t/go/pkg/mod/github.com/go-chi/chi/v5@v5.2.1/mux.go:90\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:3301\nnet/http.(*conn).serve\n\t/usr/local/go/src/net/http/server.go:2102"}
{"level":"error","ts":1745078820.8203526,"caller":"http/server.go:2294","msg":"error when applying changes","req_method":"POST","req_path":"/records","error":"CNAME records can only contain 1 target. There is likely a misconfiguration with one or more of your resources.","stacktrace":"net/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2294\ngithub.com/go-chi/chi/v5.(*Mux).routeHTTP\n\t/go/pkg/mod/github.com/go-chi/chi/v5@v5.2.1/mux.go:480\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2294\ngithub.com/go-chi/chi/v5.(*Mux).ServeHTTP\n\t/go/pkg/mod/github.com/go-chi/chi/v5@v5.2.1/mux.go:90\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:3301\nnet/http.(*conn).serve\n\t/usr/local/go/src/net/http/server.go:2102"}
{"level":"debug","ts":1745078881.8040533,"caller":"unifi/client.go:209","msg":"fetched records","count":66}
{"level":"debug","ts":1745078941.805433,"caller":"unifi/client.go:209","msg":"fetched records","count":66}
{"level":"debug","ts":1745079002.8075843,"caller":"unifi/client.go:209","msg":"fetched records","count":66}
```

### UniFiOS Version

4.2.8

### UniFi Network Version

9.1.118

### ExternalDNS Version

1.16.1

### Search

- [x] I have searched the open and closed issues for duplicates

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
