### ISSUE TITLE
Metric port name change breaks health checking

### ISSUE THREAD

**Issue by craigcabrey** [kashalls/external-dns-unifi-webhook#55]
### Bug Description

The port name changed in this upstream PR:

https://github.com/kubernetes-sigs/external-dns/pull/4691

With the current example in the README, the pod never becomes ready, since it relies on the port name `http-wh-metrics`. Renaming to `http-webhook` fixes the issue.

### ExternalDNS Configuration

```yaml
          domainFilters:
            - internal.lan
          extraArgs:
            - --ignore-ingress-tls-spec
          logLevel: debug
          policy: sync
          provider:
            name: webhook
            webhook:
              env:
                - name: UNIFI_HOST
                  value: https://unifi.irc.lan
                - name: UNIFI_USER
                  valueFrom:
                    secretKeyRef:
                      key: username
                      name: external-dns-unifi-secret
                - name: UNIFI_PASS
                  valueFrom:
                    secretKeyRef:
                      key: password
                      name: external-dns-unifi-secret
                - name: LOG_LEVEL
                  value: debug
              image:
                repository: ghcr.io/kashalls/external-dns-unifi-webhook
                tag: main
              livenessProbe:
                httpGet:
                  path: /healthz
                  port: http-webhook
                initialDelaySeconds: 10
                timeoutSeconds: 5
              readinessProbe:
                httpGet:
                  path: /readyz
                  port: http-webhook
                initialDelaySeconds: 10
                timeoutSeconds: 5
```

### ExternalDNS Logs

N/A

### Webhook Logs

N/A

### UniFiOS Version

N/A

### UniFi Network Version

N/A

### ExternalDNS Version

1.15.0

### Search

- [X] I have searched the open and closed issues for duplicates

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
