### ISSUE TITLE
UniFi will not handle wildcard cname's

### ISSUE THREAD

**Issue by kashalls** [kashalls/external-dns-unifi-webhook#58]
### Bug Description

The webhook will return `400` when trying to create a CNAME record with a wildcard key. Ex: `*.coder.ok8.sh`

UniFi returns the following output when attempting to create the record:
```json
{"record_type":"CNAME","value":"external.ok8.sh","key":"*.codeap2l.ok8.sh","enabled":true}
```
```json
{
    "code": "api.err.StaticDnsRecordInvalidParameters",
    "details": {
        "invalid_fields": [
            "key"
        ]
    },
    "errorCode": 400,
    "message": "Invalid hostname"
}
```

This should function with the External-DNS Cloudflare Provider (with warnings).

### ExternalDNS Configuration

This issue relies on the configuration of external-dns outside of the helm values. 

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: coder
  namespace: coder
spec:
  ingressClassName: external
  rules:
  - host: coder.ok8.sh
    http:
      paths:
      - backend:
          service:
            name: coder
            port:
              name: http
        path: /
        pathType: Prefix
  - host: '*.coder.ok8.sh'
    http:
      paths:
      - backend:
          service:
            name: coder
            port:
              name: http
        path: /
        pathType: Prefix
status:
  loadBalancer:
    ingress:
    - ip: 10.69.0.149
```
    
When External DNS encounters this issue, it doesn't understand what the 400 is doing per [the docs](https://github.com/kubernetes-sigs/external-dns/blob/89e7eb3c18f33e8258ecf42b9fde61048e978d1a/provider/webhook/webhook.go#L130)
    
Not sure what we should do, but it seems like our options are:
    
1. Notice the issue, attempt to warn in logs.
2. Reject it with a 500?
3. Automatically change it from a CNAME record to an A record?  

### ExternalDNS Logs

```text
time="2024-09-12T19:42:08Z" level=debug msg="Endpoints generated from ingress: coder/coder: [coder.ok8.sh 0 IN CNAME  external.ok8.sh [] *.coder.ok8.sh 0 IN CNAME  external.ok8.sh []]"
time="2024-09-12T19:42:08Z" level=debug msg="No endpoints could be generated from service coder/coder"
time="2024-09-12T19:42:08Z" level=debug msg="Failed to apply changes with code 500"
time="2024-09-12T19:42:08Z" level=error msg="Failed to do run once: soft error\nfailed to apply changes with code 500"
```

### Webhook Logs

```json
{"level":"debug","ts":1726478457.1915169,"caller":"unifi/client.go:97","msg":"Client Preforming Request","req_method":"POST","req_path":"https://10.1.0.2/proxy/network/v2/api/site/default/static-dns/"}
{"level":"debug","ts":1726478457.1915534,"caller":"log/log.go:53","msg":"Requesting https://10.1.0.2/proxy/network/v2/api/site/default/static-dns/ cookies: 1"}
{"level":"debug","ts":1726478457.2286205,"caller":"unifi/client.go:115","msg":"Client Returning Request","req_method":"POST","req_path":"https://10.1.0.2/proxy/network/v2/api/site/default/static-dns/","res_code":400}
```

### UniFiOS Version

v4.0.18

### UniFi Network Version

v8.5.1

### ExternalDNS Version

0.15.0

### Search

- [X] I have searched the open and closed issues for duplicates

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
