### ISSUE TITLE
Trouble excluding wildcard CNAME

### ISSUE THREAD

**Issue by drewburr** [kashalls/external-dns-unifi-webhook#77]
### Bug Description

I have a wildcard domain name for my Minecraft servers, `*.mc.drewburr.com`, and have external dns CNAME this record out in CloudFlare. I also have this webook looking at my services and creating the same records internally. Since Unifi does not support wildcard CNAMEs and the logs are flooded with errors, I tried to exclude this domain using `REGEXP_DOMAIN_FILTER_EXCLUSION: \*.*` and `REGEXP_DOMAIN_FILTER_EXCLUSION: \*.mc.drewburr.com` to no avail. I've also tried this with a double escape and no escape, to no avail.

Could I get assistance with understanding how to properly exclude this record?

### ExternalDNS Configuration

```yaml
external-dns:
  provider:
    name: webhook
    webhook:
      image:
        repository: ghcr.io/kashalls/external-dns-unifi-webhook
        tag: v0.3.3
      env:
        - name: UNIFI_HOST
          value: https://192.168.5.148
        - name: UNIFI_EXTERNAL_CONTROLLER
          value: 'false'
        - name: UNIFI_USER
          valueFrom:
            secretKeyRef:
              name: unifi-credentials
              key: username
        - name: UNIFI_PASS
          valueFrom:
            secretKeyRef:
              name: unifi-credentials
              key: password
        - name: LOG_LEVEL
          value: info
        - name: REGEXP_DOMAIN_FILTER_EXCLUSION
          value: \*.mc.drewburr.com
      livenessProbe:
        httpGet:
          path: /healthz
          port: http-webhook
        initialDelaySeconds: 10
        timeoutSeconds: 5
      readinessProbe:
        httpGet:
          path: /readyz
          port: http-webhook
        initialDelaySeconds: 10
        timeoutSeconds: 5
  extraArgs:
    - --ignore-ingress-tls-spec
    - --ingress-class=traefik-internal
    - --ingress-class=nginx-internal
  policy: sync
  sources: ['ingress', 'service']
  txtOwnerId: default
  txtPrefix: k8s.
  domainFilters: ['drewburr.com']

  serviceMonitor:
    enabled: true
```

### ExternalDNS Logs

```text
Defaulted container "external-dns" out of: external-dns, webhook
time="2024-12-17T06:04:26Z" level=info msg="config: {APIServerURL: KubeConfig: RequestTimeout:30s DefaultTargets:[] GlooNamespaces:[gloo-system] SkipperRouteGroupVersion:zalando.org/v1 Sources:[ingress service] Namespace: AnnotationFilter: LabelFilter: IngressClassNames:[traefik-internal nginx-internal] FQDNTemplate: CombineFQDNAndAnnotation:false IgnoreHostnameAnnotation:false IgnoreIngressTLSSpec:true IgnoreIngressRulesSpec:false GatewayNamespace: GatewayLabelFilter: Compatibility: PublishInternal:false PublishHostIP:false AlwaysPublishNotReadyAddresses:false ConnectorSourceServer:localhost:8080 Provider:webhook ProviderCacheTime:0s GoogleProject: GoogleBatchChangeSize:1000 GoogleBatchChangeInterval:1s GoogleZoneVisibility: DomainFilter:[drewburr.com] ExcludeDomains:[] RegexDomainFilter: RegexDomainExclusion: ZoneNameFilter:[] ZoneIDFilter:[] TargetNetFilter:[] ExcludeTargetNets:[] AlibabaCloudConfigFile:/etc/kubernetes/alibaba-cloud.json AlibabaCloudZoneType: AWSZoneType: AWSZoneTagFilter:[] AWSAssumeRole: AWSProfiles:[] AWSAssumeRoleExternalID: AWSBatchChangeSize:1000 AWSBatchChangeSizeBytes:32000 AWSBatchChangeSizeValues:1000 AWSBatchChangeInterval:1s AWSEvaluateTargetHealth:true AWSAPIRetries:3 AWSPreferCNAME:false AWSZoneCacheDuration:0s AWSSDServiceCleanup:false AWSZoneMatchParent:false AWSDynamoDBRegion: AWSDynamoDBTable:external-dns AzureConfigFile:/etc/kubernetes/azure.json AzureResourceGroup: AzureSubscriptionID: AzureUserAssignedIdentityClientID: AzureActiveDirectoryAuthorityHost: CloudflareProxied:false CloudflareDNSRecordsPerPage:100 CoreDNSPrefix:/skydns/ AkamaiServiceConsumerDomain: AkamaiClientToken: AkamaiClientSecret: AkamaiAccessToken: AkamaiEdgercPath: AkamaiEdgercSection: OCIConfigFile:/etc/kubernetes/oci.yaml OCICompartmentOCID: OCIAuthInstancePrincipal:false OCIZoneScope:GLOBAL OCIZoneCacheDuration:0s InMemoryZones:[] OVHEndpoint:ovh-eu OVHApiRateLimit:20 PDNSServer:http://localhost:8081 PDNSAPIKey: PDNSSkipTLSVerify:false TLSCA: TLSClientCert: TLSClientCertKey: Policy:sync Registry:txt TXTOwnerID:default TXTPrefix:k8s. TXTSuffix: TXTEncryptEnabled:false TXTEncryptAESKey: Interval:1m0s MinEventSyncInterval:5s Once:false DryRun:false UpdateEvents:false LogFormat:text MetricsAddress::7979 LogLevel:info TXTCacheInterval:0s TXTWildcardReplacement: ExoscaleEndpoint: ExoscaleAPIKey: ExoscaleAPISecret: ExoscaleAPIEnvironment:api ExoscaleAPIZone:ch-gva-2 CRDSourceAPIVersion:externaldns.k8s.io/v1alpha1 CRDSourceKind:DNSEndpoint ServiceTypeFilter:[] CFAPIEndpoint: CFUsername: CFPassword: ResolveServiceLoadBalancerHostname:false RFC2136Host: RFC2136Port:0 RFC2136Zone:[] RFC2136Insecure:false RFC2136GSSTSIG:false RFC2136CreatePTR:false RFC2136KerberosRealm: RFC2136KerberosUsername: RFC2136KerberosPassword: RFC2136TSIGKeyName: RFC2136TSIGSecret: RFC2136TSIGSecretAlg: RFC2136TAXFR:false RFC2136MinTTL:0s RFC2136BatchChangeSize:50 RFC2136UseTLS:false RFC2136SkipTLSVerify:false NS1Endpoint: NS1IgnoreSSL:false NS1MinTTLSeconds:0 TransIPAccountName: TransIPPrivateKeyFile: DigitalOceanAPIPageSize:50 ManagedDNSRecordTypes:[A AAAA CNAME] ExcludeDNSRecordTypes:[] GoDaddyAPIKey: GoDaddySecretKey: GoDaddyTTL:0 GoDaddyOTE:false OCPRouterName: IBMCloudProxied:false IBMCloudConfigFile:/etc/kubernetes/ibmcloud.json TencentCloudConfigFile:/etc/kubernetes/tencent-cloud.json TencentCloudZoneType: PiholeServer: PiholePassword: PiholeTLSInsecureSkipVerify:false PluralCluster: PluralProvider: WebhookProviderURL:http://localhost:8888 WebhookProviderReadTimeout:5s WebhookProviderWriteTimeout:10s WebhookServer:false TraefikDisableLegacy:false TraefikDisableNew:false}"
time="2024-12-17T06:04:26Z" level=info msg="Instantiating new Kubernetes client"
time="2024-12-17T06:04:26Z" level=info msg="Using inCluster-config based on serviceaccount-token"
time="2024-12-17T06:04:26Z" level=info msg="Created Kubernetes client https://10.43.0.1:443"
time="2024-12-17T06:04:27Z" level=error msg="Failed to do run once: soft error\nfailed to apply changes with code 500"
```

### Webhook Logs

```text
external-dns-provider-unifi
version: v0.3.3 (2c45e95ebd3978e178c6c512ef0e04d747c2d9a9)

{"level":"info","ts":1734415466.741563,"caller":"dnsprovider/dnsprovider.go:45","msg":"creating unifi provider with no kind of domain filters"}
{"level":"info","ts":1734415467.0410144,"caller":"server/server.go:57","msg":"starting health server","address":"0.0.0.0:8080"}
{"level":"info","ts":1734415467.0410128,"caller":"server/server.go:44","msg":"starting webhook server","address":"localhost:8888"}
{"level":"error","ts":1734415467.6613457,"caller":"unifi/provider.go:79","msg":"failed to create endpoint","name":"*.mc.drewburr.com","type":"CNAME","error":"POST request to https://192.168.5.148/proxy/network/v2/api/site/default/static-dns/ returned 400: Invalid hostname","stacktrace":"github.com/kashalls/external-dns-unifi-webhook/internal/unifi.(*Provider).ApplyChanges\n\t/build/internal/unifi/provider.go:79\ngithub.com/kashalls/external-dns-unifi-webhook/pkg/webhook.(*Webhook).ApplyChanges\n\t/build/pkg/webhook/webhook.go:145\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2220\ngithub.com/go-chi/chi/v5.(*Mux).routeHTTP\n\t/go/pkg/mod/github.com/go-chi/chi/v5@v5.1.0/mux.go:459\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2220\ngithub.com/go-chi/chi/v5.(*Mux).ServeHTTP\n\t/go/pkg/mod/github.com/go-chi/chi/v5@v5.1.0/mux.go:90\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:3210\nnet/http.(*conn).serve\n\t/usr/local/go/src/net/http/server.go:2092"}
```

### UniFiOS Version

 4.1.9

### UniFi Network Version

 8.6.9

### ExternalDNS Version

0.15.0

### Search

- [X] I have searched the open and closed issues for duplicates

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
